print('Hola, Mundo')
print(' Cual es tu nombre?')
my_name = input()
print('Es un placer conocerte, ' + my_name)
print('Lo largo que es tu nombre es :')
print(len(my_name))
print('Cual es tu edad?')
my_age = input()
print('Vas ser ' + str(int(my_age) + 1) + ' en un aNo.')
