print('Hola, Mundo')
print(' Cual es tu nombre?')
mi_nombre = input()
print('Es un placer conocerte, ' + mi_nombre)
print('Lo largo que es tu nombre es :')
print(len(mi_nombre))
print('Cual es tu edad?')
mi_edad = input()
print('Vas ser ' + str(int(mi_edad) + 1) + ' en un aNo.')
